kind: Component
metadata:
  name: emailbinding
spec:
  type: bindings.twilio.sendgrid
  version: v1
  metadata:
  - name: apiKey
    value: "#TodO:: Will add upon Demo" 
  - name: from
    value: "juliasbright@gmail.com"
  - name: name
    value: "Test Sender"
  - name: to
    value: "ex@ex.com"
  - name: subject
    value: "Hello!" 