apiVersion: apps/v1
kind: Deployment
metadata:
  name: consoleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consoleapp
  template:
    metadata:
      labels:
        app: consoleapp
    spec:
      containers:
        - name: consoleapp
          image: consoleapp:latest
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
          command: ["dapr", "run", "--app-id", "consoleapp", "--components-path", "../Config/Components", "--dapr-http-port", "3500", "--dapr-grpc-port", "50002", "--log-level", "debug", "dotnet", "ConsoleApp.dll"]
          volumeMounts:
            - name: config-volume
              mountPath: ../Config/Components
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: config-volume
          configMap:
            name: consoleapp-config
---
apiVersion: v1
kind: Service
metadata:
  name: consoleapp
spec:
  selector:
    app: consoleapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
